[package]
authors = [
    "Pascal Hertleif <killercup@gmail.com>",
    "Oliver Schneider <oli-obk@users.noreply.github.com>",
]
license = "Apache-2.0/MIT"
name = "rustfix"
description = "Automatically apply the suggestions made by rustc"
repository = "https://github.com/killercup/rustfix"
documentation = "https://docs.rs/rustfix"
readme = "README.md"
version = "0.2.0"
exclude = [
    "etc/*",
    "examples/*",
    "tests/*",
]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
replace-rs = { git = "https://github.com/killercup/replace-rs" }
failure = "0.1.1"

[dev-dependencies]
duct = "0.8.2"
env_logger = "0.5.0-rc.1"
log = "0.4.1"
pretty_assertions = "0.4.1"
tempdir = "0.3.5"
proptest = "0.7.0"

[workspace]
members = [
    "cargo-fix",
]
